import json
from pathlib import Path

import pytest


SNAPSHOT_PATH = Path("reports/graph/latest/graph-snapshot.json")


def _load_snapshot_for_future_loader_contract(path: Path):
    """Load JSON for future Graph Snapshot Loader contract tests only."""
    if not path.exists():
        raise FileNotFoundError("graph_snapshot_missing: snapshot file does not exist")

    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise ValueError("graph_snapshot_invalid_json: snapshot is not valid JSON") from exc


def _validate_snapshot_for_future_loader_contract(snapshot):
    required_keys = {"graph_schema_version", "nodes", "edges", "warnings"}

    if not isinstance(snapshot, dict):
        raise ValueError("graph_snapshot_missing_required_keys: top-level object must be a JSON object")

    missing_keys = sorted(required_keys - set(snapshot.keys()))
    if missing_keys:
        raise ValueError(
            "graph_snapshot_missing_required_keys: missing " + ", ".join(missing_keys)
        )

    node_ids = []
    for node in snapshot["nodes"]:
        node_id = node.get("id")
        node_ids.append(node_id)

    duplicate_ids = {node_id for node_id in node_ids if node_ids.count(node_id) > 1}
    if duplicate_ids:
        raise ValueError(
            "graph_snapshot_duplicate_node_id: duplicate node ids " + ", ".join(sorted(duplicate_ids))
        )

    node_id_set = set(node_ids)
    for edge in snapshot["edges"]:
        edge_from = edge.get("from")
        edge_to = edge.get("to")
        if edge_from not in node_id_set or edge_to not in node_id_set:
            raise ValueError(
                "graph_snapshot_invalid_edge_reference: edge references missing node id"
            )


def _build_future_graph_summary(snapshot):
    node_types = sorted({node.get("type") for node in snapshot["nodes"]})
    edge_types = sorted({edge.get("type") for edge in snapshot["edges"]})
    return {
        "graph_schema_version": snapshot["graph_schema_version"],
        "node_count": len(snapshot["nodes"]),
        "edge_count": len(snapshot["edges"]),
        "warning_count": len(snapshot["warnings"]),
        "node_types": node_types,
        "edge_types": edge_types,
    }


def test_future_graph_snapshot_loader_contract_validates_static_snapshot_success_case_when_present():
    if not SNAPSHOT_PATH.exists():
        pytest.skip(
            "Future Graph Snapshot Loader contract test requires existing "
            "reports/graph/latest/graph-snapshot.json; not generated by this test."
        )

    snapshot = _load_snapshot_for_future_loader_contract(SNAPSHOT_PATH)
    _validate_snapshot_for_future_loader_contract(snapshot)

    assert isinstance(snapshot, dict)
    assert "graph_schema_version" in snapshot
    assert isinstance(snapshot["nodes"], list)
    assert isinstance(snapshot["edges"], list)
    assert isinstance(snapshot["warnings"], list)


def test_future_graph_snapshot_loader_contract_returns_graph_snapshot_missing_style_error_when_snapshot_file_absent():
    missing_path = Path("__future_loader_contract_missing_snapshot__.json")

    with pytest.raises(FileNotFoundError, match="graph_snapshot_missing"):
        _load_snapshot_for_future_loader_contract(missing_path)


def test_future_graph_snapshot_loader_contract_returns_graph_snapshot_invalid_json_style_error(tmp_path):
    invalid_snapshot_path = tmp_path / "invalid.json"
    invalid_snapshot_path.write_text("{not valid json")

    with pytest.raises(ValueError, match="graph_snapshot_invalid_json"):
        _load_snapshot_for_future_loader_contract(invalid_snapshot_path)


def test_future_graph_snapshot_loader_contract_returns_graph_snapshot_missing_required_keys_style_error():
    missing_required_keys_snapshot = {
        "graph_schema_version": "1.0",
        "nodes": [],
    }

    with pytest.raises(ValueError, match="graph_snapshot_missing_required_keys"):
        _validate_snapshot_for_future_loader_contract(missing_required_keys_snapshot)


def test_future_graph_snapshot_loader_contract_returns_graph_snapshot_duplicate_node_id_style_error():
    duplicate_node_id_snapshot = {
        "graph_schema_version": "1.0",
        "nodes": [
            {"id": "n1", "type": "service"},
            {"id": "n1", "type": "service"},
        ],
        "edges": [],
        "warnings": [],
    }

    with pytest.raises(ValueError, match="graph_snapshot_duplicate_node_id"):
        _validate_snapshot_for_future_loader_contract(duplicate_node_id_snapshot)


def test_future_graph_snapshot_loader_contract_returns_graph_snapshot_invalid_edge_reference_style_error():
    invalid_edge_reference_snapshot = {
        "graph_schema_version": "1.0",
        "nodes": [
            {"id": "n1", "type": "service"},
            {"id": "n2", "type": "service"},
        ],
        "edges": [
            {"from": "n1", "to": "n3", "type": "depends_on"},
        ],
        "warnings": [],
    }

    with pytest.raises(ValueError, match="graph_snapshot_invalid_edge_reference"):
        _validate_snapshot_for_future_loader_contract(invalid_edge_reference_snapshot)


def test_future_graph_snapshot_loader_contract_builds_future_graph_summary_shape_from_valid_snapshot():
    snapshot = {
        "graph_schema_version": "1.0",
        "nodes": [
            {"id": "n1", "type": "service"},
            {"id": "n2", "type": "dataset"},
        ],
        "edges": [
            {"from": "n1", "to": "n2", "type": "depends_on"},
        ],
        "warnings": ["example warning"],
    }

    _validate_snapshot_for_future_loader_contract(snapshot)
    summary = _build_future_graph_summary(snapshot)

    assert set(summary.keys()) == {
        "graph_schema_version",
        "node_count",
        "edge_count",
        "warning_count",
        "node_types",
        "edge_types",
    }
    assert summary["graph_schema_version"] == "1.0"
    assert summary["node_count"] == 2
    assert summary["edge_count"] == 1
    assert summary["warning_count"] == 1
    assert summary["node_types"] == ["dataset", "service"]
    assert summary["edge_types"] == ["depends_on"]
