import hashlib
from pathlib import Path

import pytest

from tools.graph_projection.graph_snapshot_loader import (
    GraphSnapshotDuplicateNodeIdError,
    GraphSnapshotInvalidEdgeReferenceError,
    GraphSnapshotInvalidJsonError,
    GraphSnapshotMissingError,
    GraphSnapshotMissingRequiredKeysError,
    GraphSnapshotUnsafePathError,
    load_graph_snapshot,
    summarize_graph_snapshot,
)


SNAPSHOT_PATH = Path("reports/graph/latest/graph-snapshot.json")


def test_future_graph_snapshot_loader_contract_validates_static_snapshot_success_case_when_present():
    if not SNAPSHOT_PATH.exists():
        pytest.skip(
            "Future Graph Snapshot Loader contract test requires existing "
            "reports/graph/latest/graph-snapshot.json; not generated by this test."
        )

    snapshot = load_graph_snapshot(SNAPSHOT_PATH)

    assert isinstance(snapshot, dict)
    assert "graph_schema_version" in snapshot
    assert isinstance(snapshot["nodes"], list)
    assert isinstance(snapshot["edges"], list)
    assert isinstance(snapshot["warnings"], list)


def test_future_graph_snapshot_loader_contract_builds_future_graph_summary_shape_from_valid_snapshot():
    snapshot = {
        "graph_schema_version": "1.0",
        "nodes": [
            {"id": "n1", "type": "service"},
            {"id": "n2", "type": "dataset"},
        ],
        "edges": [
            {"source": "n1", "target": "n2", "type": "depends_on"},
        ],
        "warnings": ["example warning"],
    }

    summary = summarize_graph_snapshot(snapshot)

    assert set(summary.keys()) == {
        "graph_schema_version",
        "node_count",
        "edge_count",
        "warning_count",
        "node_types",
        "edge_types",
    }
    assert summary["graph_schema_version"] == "1.0"
    assert summary["node_count"] == 2
    assert summary["edge_count"] == 1
    assert summary["warning_count"] == 1
    assert summary["node_types"] == ["dataset", "service"]
    assert summary["edge_types"] == ["depends_on"]


def test_future_graph_snapshot_loader_contract_returns_graph_snapshot_missing_style_error_when_snapshot_file_absent():
    missing_path = Path("__future_loader_contract_missing_snapshot__.json")

    with pytest.raises(GraphSnapshotMissingError, match="graph_snapshot_missing"):
        load_graph_snapshot(missing_path)


def test_future_graph_snapshot_loader_contract_returns_graph_snapshot_invalid_json_style_error(tmp_path):
    invalid_snapshot_path = tmp_path / "invalid.json"
    invalid_snapshot_path.write_text("{not valid json", encoding="utf-8")

    with pytest.raises(GraphSnapshotInvalidJsonError, match="graph_snapshot_invalid_json"):
        load_graph_snapshot(invalid_snapshot_path)


def test_future_graph_snapshot_loader_contract_returns_graph_snapshot_missing_required_keys_style_error(tmp_path):
    snapshot_path = tmp_path / "missing_required.json"
    snapshot_path.write_text('{"graph_schema_version": "1.0", "nodes": []}', encoding="utf-8")

    with pytest.raises(GraphSnapshotMissingRequiredKeysError, match="graph_snapshot_missing_required_keys"):
        load_graph_snapshot(snapshot_path)


def test_future_graph_snapshot_loader_contract_returns_graph_snapshot_duplicate_node_id_style_error(tmp_path):
    snapshot_path = tmp_path / "duplicate_id.json"
    snapshot_path.write_text(
        '{"graph_schema_version":"1.0","nodes":[{"id":"n1","type":"service"},{"id":"n1","type":"service"}],"edges":[],"warnings":[]}',
        encoding="utf-8",
    )

    with pytest.raises(GraphSnapshotDuplicateNodeIdError, match="graph_snapshot_duplicate_node_id"):
        load_graph_snapshot(snapshot_path)


def test_future_graph_snapshot_loader_contract_returns_graph_snapshot_invalid_edge_reference_style_error(tmp_path):
    snapshot_path = tmp_path / "invalid_edge_ref.json"
    snapshot_path.write_text(
        '{"graph_schema_version":"1.0","nodes":[{"id":"n1","type":"service"}],"edges":[{"source":"n1","target":"n2","type":"depends_on"}],"warnings":[]}',
        encoding="utf-8",
    )

    with pytest.raises(GraphSnapshotInvalidEdgeReferenceError, match="graph_snapshot_invalid_edge_reference"):
        load_graph_snapshot(snapshot_path)


def test_future_graph_snapshot_loader_contract_rejects_remote_url_like_paths():
    with pytest.raises(GraphSnapshotUnsafePathError, match="graph_snapshot_unsafe_path"):
        load_graph_snapshot("http://example.com/graph.json")

    with pytest.raises(GraphSnapshotUnsafePathError, match="graph_snapshot_unsafe_path"):
        load_graph_snapshot("https://example.com/graph.json")


def test_future_graph_snapshot_loader_contract_does_not_mutate_input_file_content(tmp_path):
    snapshot_path = tmp_path / "snapshot.json"
    original_content = (
        '{"graph_schema_version":"1.0","nodes":[{"id":"n1","type":"service"},{"id":"n2","type":"dataset"}],'
        '"edges":[{"source":"n1","target":"n2","type":"depends_on"}],"warnings":[]}'
    )
    snapshot_path.write_text(original_content, encoding="utf-8")
    before_hash = hashlib.sha256(snapshot_path.read_bytes()).hexdigest()

    _snapshot = load_graph_snapshot(snapshot_path)

    after_hash = hashlib.sha256(snapshot_path.read_bytes()).hexdigest()
    assert before_hash == after_hash
